### ISSUE TITLE
Release + instructions

### ISSUE THREAD

**Issue by PhKindermann** [MartinJGeiger/pace-2024#1]
Hey Martin,

can you please create a pace-2024 release as described in the submission requirements?

Please also add a few more info on how to compile and run the code under Linux: one has to install `mono-mcs` and execute the program as `mono pace-2024.exe` (I did not know this).

Best
Philipp

**Comment by MartinJGeiger** [comment]
Dear Philipp, dear colleague,

please help with this/ please clarify: I did think that everything is included here -- https://github.com/MartinJGeiger/pace-2024 

When I navigate there, I can see the entire project.

 

The source code is in a single file, “pace-2024.cs”, which I uploaded on “optil.io”, also. There, it did compile and run. “optil.io” has mono installed, which is able (and required) to handle C# (unless you run the program under Windows alone).

Under Windows, the code can be compiled through Visual Studio (which I used foremost) or using mono (as you state below).

 

Yours,

M.

 

 

 

From: PhKindermann ***@***.***> 
Sent: Saturday, 29 June 2024 15:41
To: MartinJGeiger/pace-2024 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MartinJGeiger/pace-2024] Release + instructions (Issue #1)

 

Hey Martin,

can you please create a pace-2024 release as described in the submission requirements?

Please also add a few more info on how to compile and run the code under Linux: one has to install mono-mcs and execute the program as mono pace-2024.exe (I did not know this).

Best
Philipp

**Comment by PhKindermann** [comment]
Hey Martin,

there should be a "release" version that contains the program at the time of submission (so that things can be easily reproduced if you decide to update your program later).
See, e.g., here: https://github.com/spupyrev/pace2024-bob/releases

Best
Philipp

**Comment by MartinJGeiger** [comment]
Dear Philipp,
I hope I pushed the correct buttons, creating a release version. This is 
my first contribution through this platform, therefore, I thank you for 
your patience and help.
Yours,
M.


Am 30.06.2024 13:29, schrieb PhKindermann:

**Comment by PhKindermann** [comment]
Looks correct :)
Thank you!

**Comment by MartinJGeiger** [comment]
Thank you, Regards, M.
